import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from "@/ui/NavBar";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const links = [
  {label: 'HOME', url: '1'},
  {label: 'ABOUT', url: '2'},
  {label: 'ANTICS', url: '3'},
  {label: 'MERCH', url: '4'},
  {label: 'CONTACT', url: '5'},
  {label: 'F*MEMBERS AREA', url: '6'},
]

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-pink-300`}>
        <NavBar links={links} />
        {children}
      </body>
    </html>
  );
}
