import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from "../ui/molecules/NavBar";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <head>
      <title>F*Choir</title>
      <link rel="stylesheet" href={"https://indestructibletype.com/fonts/Jost.css"} type="text/css" charSet="utf-8" />
    </head>
      <body className={`${inter.className} bg-pink`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
